-- Esquema adoptado como baseline (generado con pg_dump y ejecutado por Flyway vía JDBC).
--
-- OJO al regenerar este archivo: pg_dump >= 17 envuelve el volcado en los meta-comandos
-- \restrict y \unrestrict, que solo entiende el cliente psql. Flyway manda el script por
-- JDBC, donde un \ inicial es un error de sintaxis y la migración falla en una BD vacía.
-- Si vuelves a volcar el esquema, elimina esas dos líneas.

CREATE TABLE public.branch_settings (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address_line character varying(255),
    business_name character varying(255),
    currency_symbol character varying(255),
    email character varying(255),
    footer_message text,
    header_note character varying(255),
    legal_name character varying(255),
    legal_note text,
    logo text,
    low_stock_threshold integer,
    paper_width integer,
    phone character varying(255),
    prices_include_tax boolean NOT NULL,
    quotation_validity_days integer,
    show_cashier boolean NOT NULL,
    show_client boolean NOT NULL,
    show_date_time boolean NOT NULL,
    show_discount boolean NOT NULL,
    show_folio boolean NOT NULL,
    show_logo boolean NOT NULL,
    show_payment_method boolean NOT NULL,
    tax_id character varying(255),
    tax_rate numeric(38,2),
    website character varying(255)
);

ALTER TABLE public.branch_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branch_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.branches (
    id bigint NOT NULL,
    address character varying(255),
    name character varying(255),
    security_pin character varying(255) NOT NULL
);

ALTER TABLE public.branches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cash_movements (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(38,2) NOT NULL,
    reason character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    registered_by_id bigint NOT NULL,
    CONSTRAINT cash_movements_type_check CHECK (((type)::text = ANY ((ARRAY['INCOME'::character varying, 'EXPENSE'::character varying])::text[])))
);

ALTER TABLE public.cash_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cash_sessions (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    closed_at timestamp(6) without time zone,
    counted_cash numeric(38,2),
    difference numeric(38,2),
    expected_cash numeric(38,2),
    opened_at timestamp(6) without time zone,
    opening_float numeric(38,2),
    status character varying(255) NOT NULL,
    closed_by_id bigint,
    opened_by_id bigint NOT NULL,
    CONSTRAINT cash_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);

ALTER TABLE public.cash_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.clients (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    age integer,
    email character varying(255),
    full_name character varying(255),
    occupation character varying(255),
    phone character varying(255),
    owner_id bigint
);

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.clinical_records (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    addition_left double precision,
    addition_right double precision,
    av_cc_ao character varying(255),
    av_cc_near character varying(255),
    av_cc_od character varying(255),
    av_cc_oi character varying(255),
    av_ph_od character varying(255),
    av_ph_oi character varying(255),
    av_sc_ao character varying(255),
    av_sc_near character varying(255),
    av_sc_od character varying(255),
    av_sc_oi character varying(255),
    axis_left integer,
    axis_right integer,
    burning boolean NOT NULL,
    cylinder_left double precision,
    cylinder_right double precision,
    date date NOT NULL,
    diabetes boolean NOT NULL,
    family_history boolean NOT NULL,
    height double precision,
    hypertension boolean NOT NULL,
    itching boolean NOT NULL,
    last_rx_date date,
    notes character varying(1000),
    photophobia_artificial boolean NOT NULL,
    photophobia_solar boolean NOT NULL,
    pupillary_distance double precision,
    secretion boolean NOT NULL,
    sphere_left double precision,
    sphere_right double precision,
    tearing boolean NOT NULL,
    uses_contacts boolean NOT NULL,
    uses_glasses boolean NOT NULL,
    client_id bigint NOT NULL,
    optometrist_id bigint
);

ALTER TABLE public.clinical_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clinical_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.lens_base_prices (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    design_type character varying(255) NOT NULL,
    price numeric(38,2) NOT NULL,
    CONSTRAINT lens_base_prices_design_type_check CHECK (((design_type)::text = ANY ((ARRAY['MONOFOCAL'::character varying, 'BIFOCAL_FLAT_TOP'::character varying, 'BIFOCAL_INVISIBLE'::character varying, 'PROGRESSIVE'::character varying])::text[])))
);

ALTER TABLE public.lens_base_prices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lens_base_prices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payments (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(38,2),
    method character varying(255),
    reference_code character varying(255),
    sale_id bigint NOT NULL,
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['CASH'::character varying, 'CARD'::character varying, 'CREDIT_CARD'::character varying, 'DEBIT_CARD'::character varying, 'TRANSFER'::character varying])::text[])))
);

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.price_matrices (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    name character varying(255)
);

ALTER TABLE public.price_matrices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_matrices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.price_rules (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    adjustment numeric(38,2),
    condition_type character varying(255),
    material_index character varying(255),
    max_val double precision,
    min_val double precision,
    matrix_id bigint
);

ALTER TABLE public.price_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    base_price numeric(38,2) NOT NULL,
    brand character varying(255) NOT NULL,
    category character varying(255),
    color character varying(255),
    duration integer,
    model character varying(255) NOT NULL,
    sku character varying(255) NOT NULL,
    stock_quantity integer,
    type character varying(255) NOT NULL,
    cost numeric DEFAULT 0,
    CONSTRAINT products_type_check CHECK (((type)::text = ANY ((ARRAY['FRAME'::character varying, 'LENS'::character varying, 'SERVICE'::character varying, 'ACCESSORY'::character varying, 'MATERIAL'::character varying])::text[])))
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.promotions (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    code character varying(255),
    description character varying(255),
    end_date date,
    name character varying(255),
    start_date date,
    type character varying(255),
    value numeric(38,2),
    CONSTRAINT promotions_type_check CHECK (((type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying])::text[])))
);

ALTER TABLE public.promotions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sale_items (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    product_name_snapshot character varying(255),
    quantity integer,
    subtotal numeric(38,2),
    unit_price numeric(38,2),
    clinical_record_id bigint,
    product_id bigint NOT NULL,
    sale_id bigint NOT NULL
);

ALTER TABLE public.sale_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sales (
    id bigint NOT NULL,
    branch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_parked boolean NOT NULL,
    paid_amount numeric(38,2),
    status character varying(255),
    total_amount numeric(38,2),
    client_id bigint,
    seller_id bigint NOT NULL,
    discount_amount numeric(38,2),
    discount_name character varying(255),
    CONSTRAINT sales_status_check CHECK (((status)::text = ANY ((ARRAY['QUOTATION'::character varying, 'PENDING'::character varying, 'IN_PROCESS'::character varying, 'READY_TO_PICK'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE public.sales_goals (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    period_month integer NOT NULL,
    owner_id bigint NOT NULL,
    target_amount numeric(38,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    period_year integer NOT NULL
);

ALTER TABLE public.sales_goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_branch_roles (
    id bigint NOT NULL,
    role character varying(255),
    branch_id bigint,
    user_id bigint,
    CONSTRAINT user_branch_roles_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'MANAGER'::character varying, 'OPTOMETRIST'::character varying, 'SELLER'::character varying])::text[])))
);

ALTER TABLE public.user_branch_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_branch_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    email character varying(255),
    full_name character varying(255),
    password character varying(255),
    quick_pin character varying(100),
    username character varying(255),
    activation_code character varying(10),
    activation_code_expires_at timestamp(6) without time zone,
    credentials_set boolean DEFAULT true
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.branch_settings
    ADD CONSTRAINT branch_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT branches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cash_movements
    ADD CONSTRAINT cash_movements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cash_sessions
    ADD CONSTRAINT cash_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.clinical_records
    ADD CONSTRAINT clinical_records_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.lens_base_prices
    ADD CONSTRAINT lens_base_prices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.price_matrices
    ADD CONSTRAINT price_matrices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.price_rules
    ADD CONSTRAINT price_rules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT promotions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT sale_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sales_goals
    ADD CONSTRAINT sales_goals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.sales_goals
    ADD CONSTRAINT ukn8hgo763nl7h4kyc8gp8u0n4m UNIQUE (owner_id, period_year, period_month);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

ALTER TABLE ONLY public.user_branch_roles
    ADD CONSTRAINT user_branch_roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT fk1kh9hqfkteceuf8f3m7kebsrc FOREIGN KEY (clinical_record_id) REFERENCES public.clinical_records(id);

ALTER TABLE ONLY public.clinical_records
    ADD CONSTRAINT fk1womn0e5rs6nm8ckekye2n1b5 FOREIGN KEY (client_id) REFERENCES public.clients(id);

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fk51eqltjywqvwqy3mjiobehi7s FOREIGN KEY (seller_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT fk7tcpbc5c5mpnm8fl2phl8ep7l FOREIGN KEY (sale_id) REFERENCES public.sales(id);

ALTER TABLE ONLY public.price_rules
    ADD CONSTRAINT fk7y6vpvvivwf60he026hgba9if FOREIGN KEY (matrix_id) REFERENCES public.price_matrices(id);

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT fk8g0sjiqs7tg055o06p6wawu39 FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.cash_movements
    ADD CONSTRAINT fk9l7jimeohw6tskm4q8hrmro90 FOREIGN KEY (registered_by_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fkbbif9cb3ecyusyms54yvwlhd5 FOREIGN KEY (client_id) REFERENCES public.clients(id);

ALTER TABLE ONLY public.user_branch_roles
    ADD CONSTRAINT fkfrmo2tqqtf82buyxhtnqnt6a7 FOREIGN KEY (branch_id) REFERENCES public.branches(id);

ALTER TABLE ONLY public.clinical_records
    ADD CONSTRAINT fkghu4hb1uy0k1pop72qku0ximq FOREIGN KEY (optometrist_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkirxc2n6ymen0s4s4296xujgoj FOREIGN KEY (branch_id) REFERENCES public.branches(id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkl5ax948m03dbdcy3i0aql4jil FOREIGN KEY (sale_id) REFERENCES public.sales(id);

ALTER TABLE ONLY public.cash_sessions
    ADD CONSTRAINT fkl918r7fup1kp66d3rtfvkrl3d FOREIGN KEY (closed_by_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.cash_sessions
    ADD CONSTRAINT fkm0ne8fihcel97f3bb01cp6t7m FOREIGN KEY (opened_by_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_branch_roles
    ADD CONSTRAINT fkpyr20m44wtmxio1kuecls25ai FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fkrhimhek4ehsu31ujgod41qnhx FOREIGN KEY (branch_id) REFERENCES public.branches(id);

