-- Bitácora de auditoría: registro append-only de acciones sensibles
-- (dinero, acceso e identidad, gestión de empleados).
-- branch_id es NULLABLE a propósito: las acciones del Hub global no tienen sucursal.
CREATE TABLE audit_log (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action         varchar(50)  NOT NULL,
    entity_type    varchar(50),
    entity_id      bigint,
    branch_id      bigint,
    actor_user_id  bigint,
    actor_username varchar(255),
    details        varchar(2000),
    ip_address     varchar(45),
    created_at     timestamp(6) without time zone NOT NULL
);

-- Consulta típica: bitácora de una sucursal ordenada por fecha descendente.
CREATE INDEX idx_audit_log_branch_created ON audit_log (branch_id, created_at);
-- Filtro por tipo de acción.
CREATE INDEX idx_audit_log_action ON audit_log (action);
