-- Llaves de idempotencia para las operaciones de dinero (crear venta, agregar pago, devolver).
-- Evitan que un reintento de red o un doble clic generen un duplicado: el segundo intento
-- reconoce la llave y devuelve el resultado del primero.
CREATE TABLE idempotency_key (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    bigint       NOT NULL,
    scope        varchar(30)  NOT NULL,
    key_value    varchar(100) NOT NULL,
    request_hash varchar(64)  NOT NULL,
    status       varchar(20)  NOT NULL,
    resource_id  bigint,
    created_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone
);

-- El corazón del mecanismo: la carrera entre dos intentos simultáneos la resuelve
-- este índice único, no la aplicación.
ALTER TABLE idempotency_key
    ADD CONSTRAINT uk_idempotency_key UNIQUE (branch_id, scope, key_value);

-- Soporta la purga programada de llaves expiradas.
CREATE INDEX idx_idempotency_key_created ON idempotency_key (created_at);
