-- Devoluciones/reembolsos: reingreso de mercancía, reversa en caja y ajuste del saldo de la venta.
--
-- Modelo: total_amount y paid_amount se conservan como historia bruta de la venta original.
-- Lo devuelto se expresa aparte, en dos conceptos que NO son lo mismo:
--   returned_amount  = valor de la mercancía que regresó (descuento prorrateado)
--   refunded_amount  = dinero que efectivamente salió de la caja
-- Si la venta traía saldo pendiente, devolver mercancía baja la deuda sin mover dinero.
-- El DEFAULT deja en cero las ventas históricas, que por definición no tienen devoluciones.
ALTER TABLE public.sales
    ADD COLUMN returned_amount numeric(38,2) DEFAULT 0 NOT NULL,
    ADD COLUMN refunded_amount numeric(38,2) DEFAULT 0 NOT NULL;

-- El CHECK del baseline enumera los estados válidos: hay que recrearlo para admitir
-- los dos nuevos, o cualquier devolución falla al guardar.
ALTER TABLE public.sales DROP CONSTRAINT sales_status_check;
ALTER TABLE public.sales ADD CONSTRAINT sales_status_check CHECK (
    (status)::text = ANY ((ARRAY[
        'QUOTATION'::character varying,
        'PENDING'::character varying,
        'IN_PROCESS'::character varying,
        'READY_TO_PICK'::character varying,
        'COMPLETED'::character varying,
        'CANCELLED'::character varying,
        'PARTIALLY_RETURNED'::character varying,
        'RETURNED'::character varying
    ])::text[])
);

CREATE TABLE public.refunds (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id      bigint        NOT NULL,
    sale_id        bigint        NOT NULL REFERENCES public.sales (id),
    returned_value numeric(38,2) NOT NULL,
    amount         numeric(38,2) NOT NULL,
    method         varchar(20),
    reason         varchar(255)  NOT NULL,
    processed_by   bigint        NOT NULL REFERENCES public.users (id),
    created_at     timestamp(6) without time zone,
    updated_at     timestamp(6) without time zone
);

CREATE TABLE public.refund_items (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    bigint        NOT NULL,
    refund_id    bigint        NOT NULL REFERENCES public.refunds (id),
    sale_item_id bigint        NOT NULL REFERENCES public.sale_items (id),
    quantity     integer       NOT NULL,
    amount       numeric(38,2) NOT NULL,
    restocked    boolean       NOT NULL,
    created_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone
);

-- Devoluciones de una venta (detalle) y de una ventana de tiempo (arqueo de caja).
CREATE INDEX idx_refunds_sale ON public.refunds (sale_id);
CREATE INDEX idx_refunds_branch_created ON public.refunds (branch_id, created_at);
-- Cuánto se ha devuelto ya de cada partida.
CREATE INDEX idx_refund_items_sale_item ON public.refund_items (sale_item_id);
