-- Fase 3 — ciclo de inventario: compras (entradas con costo) y ajustes (mermas/correcciones).
--
-- Todo vive por sucursal, igual que los productos y su stock: cada sucursal compra a quien le
-- surte y ajusta su propio anaquel.

CREATE TABLE public.suppliers (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    bigint       NOT NULL,
    name         varchar(150) NOT NULL,
    contact_name varchar(150),
    phone        varchar(30),
    email        varchar(150),
    notes        varchar(500),
    active       boolean      NOT NULL DEFAULT true,
    created_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone
);

-- Pedir no es tener: estas tablas no mueven stock por sí solas. El inventario y el costo
-- promedio cambian únicamente al recibir mercancía.
CREATE TABLE public.purchase_orders (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id      bigint      NOT NULL,
    supplier_id    bigint      NOT NULL REFERENCES public.suppliers (id),
    status         varchar(30) NOT NULL,
    reference_code varchar(100),
    expected_date  date,
    notes          varchar(500),
    created_by     bigint      NOT NULL REFERENCES public.users (id),
    received_at    timestamp(6) without time zone,
    created_at     timestamp(6) without time zone,
    updated_at     timestamp(6) without time zone
);

-- received_cost_total acumula lo que costó cada recepción a su propio precio: si la segunda
-- parte del pedido llega más cara, multiplicar cantidad × unit_cost repreciaría lo que ya
-- había entrado e inflaría la deuda con el proveedor.
CREATE TABLE public.purchase_order_items (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id           bigint        NOT NULL,
    purchase_order_id   bigint        NOT NULL REFERENCES public.purchase_orders (id),
    product_id          bigint        NOT NULL REFERENCES public.products (id),
    quantity_ordered    integer       NOT NULL,
    quantity_received   integer       NOT NULL DEFAULT 0,
    unit_cost           numeric(38,2) NOT NULL,
    received_cost_total numeric(38,2) NOT NULL DEFAULT 0,
    created_at          timestamp(6) without time zone,
    updated_at          timestamp(6) without time zone
);

-- Rastro de por qué el stock del sistema dejó de coincidir con el anaquel.
CREATE TABLE public.inventory_adjustments (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id          bigint        NOT NULL,
    product_id         bigint        NOT NULL REFERENCES public.products (id),
    reason             varchar(30)   NOT NULL,
    note               varchar(500),
    previous_quantity  integer       NOT NULL,
    new_quantity       integer       NOT NULL,
    delta              integer       NOT NULL,
    unit_cost_snapshot numeric(38,2) NOT NULL,
    adjusted_by        bigint        NOT NULL REFERENCES public.users (id),
    created_at         timestamp(6) without time zone,
    updated_at         timestamp(6) without time zone
);

-- Listados por sucursal ordenados por fecha (la consulta de todas las pantallas nuevas).
CREATE INDEX idx_suppliers_branch ON public.suppliers (branch_id);
CREATE INDEX idx_purchase_orders_branch_created ON public.purchase_orders (branch_id, created_at);
CREATE INDEX idx_purchase_orders_supplier ON public.purchase_orders (supplier_id);
CREATE INDEX idx_purchase_order_items_order ON public.purchase_order_items (purchase_order_id);
CREATE INDEX idx_inventory_adjustments_branch_created ON public.inventory_adjustments (branch_id, created_at);
CREATE INDEX idx_inventory_adjustments_product ON public.inventory_adjustments (product_id);
