-- Fase 4 — recuperación de contraseña self-service del dueño.
--
-- Sin branch_id a propósito: el token pertenece a la CUENTA, no a una sucursal, y se emite
-- antes de iniciar sesión (no hay contexto de sucursal en ese momento).
--
-- Del token solo se guarda su hash SHA-256: quien lo tenga puede tomar la cuenta, así que es
-- un secreto equivalente a una contraseña. Si la base se filtrara, los hashes no sirven.

CREATE TABLE public.password_reset_tokens (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash varchar(64) NOT NULL UNIQUE,
    user_id    bigint      NOT NULL,
    expires_at timestamp(6) NOT NULL,
    used_at    timestamp(6),
    created_at timestamp(6) NOT NULL,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

-- La búsqueda por hash es la del camino crítico (canjear el enlace); el índice del UNIQUE ya
-- la cubre. Este otro sirve para invalidar en bloque los tokens vivos de un usuario.
CREATE INDEX idx_password_reset_user ON public.password_reset_tokens (user_id, used_at);
