-- Fase A — alta de ópticas: administrador de plataforma y estado de suscripción.
--
-- POR QUÉ platform_admin ES UNA COLUMNA Y NO UN ROL:
-- Los roles viven en user_branch_roles, es decir, SIEMPRE dentro de una óptica. Las
-- autoridades de Spring se derivan de esas filas (ver AuthTokenFilter) y todas las consultas
-- del sistema se acotan a las sucursales del usuario. El administrador de plataforma no
-- pertenece a ninguna óptica: se le da CERO filas en user_branch_roles y, por construcción,
-- no puede leer ventas, clientes ni expedientes de nadie. La restricción no depende de que
-- alguien se acuerde de escribir un chequeo en cada endpoint nuevo — es estructural.
--
-- Además, user_branch_roles.role tiene un CHECK que fija los cuatro roles existentes
-- ('OWNER','MANAGER','OPTOMETRIST','SELLER'). Agregar un quinto valor al enum de Java
-- compilaría y arrancaría sin protestar, y Postgres rechazaría cada inserción en tiempo de
-- ejecución. Este diseño no toca ese CHECK ni los roles que ya funcionan.

ALTER TABLE public.users
    ADD COLUMN platform_admin boolean NOT NULL DEFAULT false;

-- Parcial: solo indexa las pocas filas que son true. El resto de la tabla no paga el costo.
CREATE INDEX idx_users_platform_admin ON public.users (platform_admin) WHERE platform_admin;

-- Estado comercial de cada cliente.
--
-- Cuelga del DUEÑO, no de la sucursal: una óptica con tres sucursales es un solo cliente y
-- una sola suscripción. Sin branch_id, por lo mismo que password_reset_tokens.
--
-- Hoy estos campos los llena a mano el administrador desde el panel. Son exactamente los que
-- una pasarela de pago escribiría sola el día que se integre: el resto del sistema no se
-- entera del cambio. Por eso NO hay aquí planes, precios ni historial de pagos — eso llega
-- con el cobro automático, y todavía no hay a quién cobrarle.
CREATE TABLE public.subscription (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id bigint       NOT NULL,
    status        varchar(20)  NOT NULL,
    valid_until   date,
    notes         text,
    created_at    timestamp(6) NOT NULL,
    updated_at    timestamp(6),
    CONSTRAINT fk_subscription_owner FOREIGN KEY (owner_user_id)
        REFERENCES public.users(id) ON DELETE CASCADE,
    -- Sin CHECK sobre status a propósito: es justo la trampa que tiene user_branch_roles.role.
    -- El enum de Java es la autoridad; un CHECK aquí obligaría a una migración por cada estado
    -- nuevo y fallaría en producción, no al compilar.
    CONSTRAINT uq_subscription_owner UNIQUE (owner_user_id)
);

CREATE INDEX idx_subscription_valid_until ON public.subscription (valid_until);
