-- Fase B — solicitudes de acceso desde la página pública.
--
-- La puerta de entrada es pública, pero el REGISTRO no: nadie crea una óptica solo. El
-- prospecto deja sus datos, la solicitud aparece en el panel y el administrador decide.
-- Sin esto, cualquiera en internet podría crear inquilinos en el servidor, y expondría el
-- aislamiento entre inquilinos antes de haberlo probado con dos clientes reales.
--
-- Sin branch_id: una solicitud todavía no es una óptica; es alguien preguntando.

CREATE TABLE public.registration_request (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name  varchar(150) NOT NULL,
    contact_name   varchar(150) NOT NULL,
    email          varchar(150),
    phone          varchar(30),
    city           varchar(100),
    message        text,
    status         varchar(20)  NOT NULL,
    -- Consentimiento del aviso de privacidad. Se guarda el CUÁNDO, no un booleano: si algún
    -- día hay que demostrar que alguien aceptó, "true" no dice nada y una fecha sí. Es dato
    -- personal lo que se recoge aquí, así que esto no es opcional.
    consent_at     timestamp(6),
    -- Se guardan para poder cortar abuso desde el panel, no para perfilar a nadie.
    source_ip      varchar(45),
    created_at     timestamp(6) NOT NULL,
    reviewed_at    timestamp(6),
    reviewed_by    varchar(100),
    review_note    text,
    -- Óptica creada al aprobar: deja el rastro de qué solicitud se convirtió en qué cliente.
    created_owner_id bigint,
    CONSTRAINT fk_registration_request_owner FOREIGN KEY (created_owner_id)
        REFERENCES public.users(id) ON DELETE SET NULL
);

-- La consulta del panel es "las pendientes, primero las más viejas": ese es el orden en que
-- hay que atenderlas, y a nadie le gusta que su solicitud se quede al fondo.
CREATE INDEX idx_registration_request_status ON public.registration_request (status, created_at);
